USE skillmatch_uba;

INSERT INTO materias (codigo, nombre) VALUES
('COM01','Análisis Matemático II'),
('COM02','Economía y Organización'),
('COM03','Electricidad y Magnetismo'),
('COM04','Electricidad, Magnetismo y Calor'),
('COM05','Física de los Sistemas de Partículas'),
('COM06','Higiene y Seguridad'),
('COM07','Impacto Social, Ambiental y Desarrollo Sustentable'),
('COM08','Introducción a la Ciencia de Datos'),
('COM09','Legislación y Ejercicio Profesional'),
('COM10','Modelación Numérica'),
('COM11','Probabilidad y Estadística'),
('COM12','Química Básica'),
('COM13','Taller de Electrónica'),
('COM14','Álgebra Lineal'),
('BIO01','Introducción a la Bioingeniería'),
('BIO02','Anatomía e Histología Funcional'),
('BIO03','Algoritmos y Programación'),
('BIO04','Planificación de Proyectos'),
('BIO05','Química de los Compuestos Orgánicos'),
('BIO06','Señales y Sistemas'),
('BIO07','Sistemas Moleculares, Celulares y Tisulares'),
('BIO08','Física de Sólidos y Nuclear'),
('BIO09','Control Automático'),
('BIO10','Análisis de Circuitos'),
('BIO11','Procesos Estocásticos'),
('BIO12','Introducción a los Dispositivos Electrónicos'),
('BIO13','Sistemas Fisiológicos y sus Modelos'),
('BIO14','Introducción a la Mecánica del Continuo'),
('BIO15','Taller de Procesamiento de Señales'),
('BIO16','Circuitos Microelectrónicos'),
('BIO17','Introducción a los Sistemas Embebidos'),
('BIO18','Gestión de Proyectos'),
('BIO19','Introducción a la Biomecánica'),
('BIO20','Instrumentación y Equipamiento para Diagnóstico y Tratamiento'),
('BIO21','Introducción a los Biomateriales'),
('BIO22','Análisis y Procesamiento de Señales en Bioingeniería'),
('BIO23','Imágenes en Bioingeniería'),
('BIO24','Tecnología de Asistencia y Prótesis'),
('BIO25','Ingeniería Clínica y Hospitalaria'),
('INF01','Fundamentos de Programación'),
('INF02','Introducción al Desarrollo de Software'),
('INF03','Organización del Computador'),
('INF04','Algoritmos y Estructuras de Datos'),
('INF05','Teoría de Algoritmos'),
('INF06','Sistemas Operativos'),
('INF07','Paradigmas de Programación'),
('INF08','Base de Datos'),
('INF09','Taller de Programación'),
('INF10','Ingeniería de Software I'),
('INF11','Ciencia de Datos'),
('INF12','Gestión del Desarrollo de Sistemas Informáticos'),
('INF13','Programación Concurrente'),
('INF14','Redes'),
('INF15','Física para Informática'),
('INF16','Empresas de Base Tecnológica I'),
('INF17','Ingeniería de Software II'),
('INF18','Sistemas Distribuidos I'),
('INF19','Taller de Seguridad Informática'),
('INF20','Empresas de Base Tecnológica II'),
('ENE01','Introducción a la Ingeniería en Energía Eléctrica'),
('ENE02','Estática y Resistencia de Materiales'),
('ENE03','Física de Sólidos y Nuclear'),
('ENE04','Electrotecnia'),
('ENE05','Análisis Matemático III'),
('ENE06','Campos Electromagnéticos'),
('ENE07','Circuitos y Sistemas de Control'),
('ENE08','Medidas Eléctricas'),
('ENE09','Termodinámica / Mecánica de Fluidos y Máquinas'),
('ENE10','Máquinas Eléctricas I'),
('ENE11','Tecnología de Materiales Eléctricos'),
('ENE12','Diagnósticos Eléctricos y Ensayos'),
('ENE13','Máquinas Eléctricas II'),
('ENE14','Mecánica Aplicada'),
('ENE15','Instalaciones de Baja Tensión y Luminotecnia'),
('ENE16','Sistemas Eléctricos de Potencia'),
('ENE17','Conversión Estática de la Energía Eléctrica'),
('ENE18','Economía de la Energía Eléctrica'),
('ENE19','Transmisión y Distribución de la Energía Eléctrica'),
('ENE20','Generación de Energía Eléctrica'),
('ENE21','Protecciones Eléctricas y Equipos de Maniobra'),
('MEC01','Introducción a la Ingeniería Mecánica'),
('MEC02','Conocimiento de Materiales Metálicos'),
('MEC03','Diseño Mecánico'),
('MEC04','Mecánica Clásica del Cuerpo Rígido'),
('MEC05','Mecanismos'),
('MEC06','Introducción a la Mecánica del Sólido Deformable'),
('MEC07','Termodinámica'),
('MEC08','Análisis Matemático III'),
('MEC09','Conocimiento de Materiales No Metálicos'),
('MEC10','Ensayos Industriales'),
('MEC11','Electrotecnia General'),
('MEC12','Taller de Manufactura Mecánica'),
('MEC13','Mecánica de Fluidos'),
('MEC14','Proyecto de Instrumentación'),
('MEC15','Máquinas Térmicas'),
('MEC16','Tecnología Mecánica'),
('MEC17','Sistemas de Almacenamiento, Transferencia de Calor y Masa y sus Instalaciones'),
('MEC18','Daño y Fractura de Elementos Mecánicos'),
('MEC19','Máquinas Eléctricas'),
('MEC20','Sistemas de Control y Automatización'),
('MEC21','Turbomáquinas'),
('MEC22','Proyecto de Instalaciones Industriales'),
('MEC23','Elementos de Máquinas'),
('MEC24','Mantenimiento y Calidad'),
('NAV01','Óptica'),
('NAV02','Introducción a la Ingeniería Naval'),
('NAV03','Medios de Representación'),
('NAV04','Estática'),
('NAV05','Dibujo Naval y Mecánico'),
('NAV06','Resistencia de Materiales'),
('NAV07','Termodinámica'),
('NAV08','Conocimiento de Materiales'),
('NAV09','Electrotecnia'),
('NAV10','Máquinas e Instalaciones Eléctricas'),
('NAV11','Estabilidad del Buque'),
('NAV12','Mecánica de Fluidos'),
('NAV13','Teoría de Estructuras'),
('NAV14','Diseño de Estructuras de Buques'),
('NAV15','Sistemas Auxiliares Navales'),
('NAV16','Mecanismos y Elementos de Máquinas'),
('NAV17','Resistencia y Propulsión de Buques'),
('NAV18','Sistemas Inherentes a la Operación del Buque'),
('NAV19','Tecnología de Astilleros'),
('NAV20','Análisis Estructural de Buques'),
('NAV21','Mecánica Clásica del Cuerpo Rígido'),
('NAV22','Plantas Propulsoras'),
('NAV23','Proyecto de Buques Mercantes'),
('NAV24','Prácticas en Astilleros'),
('NAV25','Dinámica de Estructuras de Buques'),
('ELE01','Introducción a la Ingeniería Electrónica'),
('ELE02','Algoritmos y Programación'),
('ELE03','Introducción a los Dispositivos Electrónicos'),
('ELE04','Sistemas Digitales'),
('ELE05','Señales y Sistemas'),
('ELE06','Análisis de Circuitos'),
('ELE07','Redes de Comunicaciones'),
('ELE08','Planificación de Proyectos'),
('ELE09','Circuitos Microelectrónicos'),
('ELE10','Procesos Estocásticos'),
('ELE11','Control Automático'),
('ELE12','Taller de Sistemas Embebidos'),
('ELE13','Química y Electroquímica'),
('ELE14','Electromagnetismo Aplicado'),
('ELE15','Taller de Automatización y Control'),
('ELE16','Taller de Procesamiento de Señales'),
('ELE17','Dispositivos Semiconductores'),
('ELE18','Taller de Comunicaciones Digitales'),
('ELE19','Taller de Diseño de Circuitos Electrónicos'),
('ELE20','Gestión de Proyectos Electrónicos'),
('QUI01','Química General'),
('QUI02','Introducción a Ingeniería Química'),
('QUI03','Química Inorgánica'),
('QUI04','Fundamentos de Procesos Químicos'),
('QUI05','Óptica'),
('QUI06','Termodinámica de los Procesos'),
('QUI07','Química Orgánica'),
('QUI08','Fenómenos de Transporte'),
('QUI09','Operaciones Unitarias de Transferencia de Cantidad de Movimiento y Energía'),
('QUI10','Química Física'),
('QUI11','Química Analítica Instrumental'),
('QUI12','Laboratorio de Operaciones y Procesos'),
('QUI13','Operaciones Unitarias de Transferencia de Materia'),
('QUI14','Instalaciones de Plantas de Procesos'),
('QUI15','Diseño de Reactores'),
('QUI16','Dinámica y Control de Procesos'),
('QUI17','Evaluación de Proyectos de Plantas Químicas'),
('QUI18','Ingeniería de Bioprocesos'),
('QUI19','Diseño de Procesos'),
('QUI20','Emisiones de Contaminantes Químicos y Biológicos'),
('CIV01','Introducción a la Ingeniería Civil'),
('CIV02','Estática'),
('CIV03','Introducción al Transporte, la Movilidad y el Urbanismo'),
('CIV04','Resistencia de Materiales'),
('CIV05','Hidráulica General'),
('CIV06','Calor y Termodinámica'),
('CIV07','Análisis Estructural'),
('CIV08','Comportamiento de Materiales'),
('CIV09','Hidráulica Aplicada'),
('CIV10','Mecánica de Suelos y Geología'),
('CIV11','Introducción a la Ciencia de Datos para Ingeniería Civil'),
('CIV12','Diseño Geométrico de Obras Lineales'),
('CIV13','Construcciones Civiles y Arquitectura'),
('CIV14','Topografía y Geodesia'),
('CIV15','Economía y Evaluación de Proyectos de Ingeniería Civil'),
('CIV16','Materiales Viales y Pavimentos I'),
('CIV17','Hidrología Aplicada'),
('CIV18','Hormigón I'),
('CIV19','Sistemas de Transporte Guiado I'),
('CIV20','Puertos y Vías Navegables I'),
('CIV21','Aeropuertos I'),
('CIV22','Ingeniería Sanitaria I'),
('CIV23','Estructuras Metálicas'),
('CIV24','Instalaciones de las Obras Civiles'),
('CIV25','Cimentaciones'),
('CIV26','Hormigón II'),
('CIV27','Gestión Socioambiental de las Obras Civiles'),
('CIV28','Gerenciamiento y Organización de Obras Civiles'),
('PET01','Introducción a la Ingeniería en Petróleo'),
('PET02','Geología General'),
('PET03','Fluidodinámica de los Hidrocarburos'),
('PET04','Química de los Hidrocarburos'),
('PET05','Geofísica'),
('PET06','Termodinámica de los Hidrocarburos'),
('PET07','Electrotecnia, Máquinas e Instalaciones Eléctricas'),
('PET08','Estática y Resistencia de Materiales'),
('PET09','Geología de los Hidrocarburos'),
('PET10','Propiedades de la Roca y los Fluidos de Reservorios'),
('PET11','Ingeniería de Reservorios'),
('PET12','Perforación e Intervención de Pozos I'),
('PET13','Procesamiento de Hidrocarburos en Yacimiento'),
('PET14','Sustentabilidad de Proyectos de Hidrocarburos'),
('PET15','Interpretación de Registro de Pozos'),
('PET16','Perforación e Intervención de Pozos II'),
('PET17','Producción de Hidrocarburos'),
('PET18','Proyecto de Instalaciones de Superficie'),
('PET19','Estimulación de Formaciones'),
('PET20','Ingeniería de Reservorios No Convencionales'),
('PET21','Recuperación Secundaria y Asistida de Petróleo'),
('PET22','Industrialización de los Hidrocarburos'),
('PET23','Transporte y Distribución de Hidrocarburos'),
("LAS01", "Álgebra II"),
("LAS02", "Algoritmos y Programación I"),
("LAS03", "Matemática Discreta"),
("LAS04", "Organización del Computador"),
("LAS05", "Algoritmos y Programación II"),
("LAS06", "Probabilidad y Estadística B"),
("LAS07", "Estructuras y Procesos Organizacionales"),
("LAS08", "Organización de Datos"),
("LAS09", "Algoritmos y Programación III"),
("LAS10", "Economía de las Organizaciones"),
("LAS11", "Sistemas Operativos"),
("LAS12", "Métodos y Modelos en la Ingeniería de Software I"),
("LAS13", "Taller de Programación"),
("LAS14", "Modelos y Optimización I"),
("LAS15", "Métodos y Modelos en la Ingeniería de Software II"),
("LAS16", "Base de Datos"),
("LAS17", "Administración de las Organizaciones"),
("LAS18", "Modelos y Optimización II"),
("LAS19", "Administración y Control de Proyectos Informáticos I"),
("LAS20", "Diseño, Operación y Gestión de Servicios Informáticos"),
("LAS21", "Redes y Aplicaciones Distribuidas"),
("LAS22", "Legislación y Ejercicio Profesional en Sistemas e Informática"),
("LAS23", "Estándares de Calidad y Modelos de Referencia"),
("AGR01", "Sistemas de Coordenadas"),
("AGR02", "Sistemas de Representación Orientado a la Agrimensura"),
("AGR03", "Dibujo Cartográfico y Topográfico"),
("AGR04", "Introducción a la Ingeniería en Agrimensura"),
("AGR05", "Instrumental Topográfico"),
("AGR06", "Derecho para Agrimensura"),
("AGR07", "Elementos de Construcción"),
("AGR08", "Métodos Topográficos"),
("AGR09", "Cálculo de Compensación"),
("AGR10", "Cartografía"),
("AGR11", "Geodesia Astronómica y Mediciones Precisas"),
("AGR12", "Relevamientos Topográficos"),
("AGR13", "Geodesia Geométrica y Satelital"),
("AGR14", "Fotogrametría"),
("AGR15", "Normativa de Mensura y Propiedad Horizontal"),
("AGR16", "Georreferenciación de Trabajos Topográficos y Geodésicos"),
("AGR17", "Fotogrametría Digital"),
("AGR18", "Aplicación Legal de la Agrimensura"),
("AGR19", "Geografía Física y Geología"),
("AGR20", "Sistemas de Información Geográfica"),
("AGR21", "Catastro"),
("AGR22", "Mensuras"),
("AGR23", "Teledetección para Agrimensura"),
("AGR24", "Información Rural"),
("AGR25", "Topografía de Obra"),
("AGR26", "Mensuras Aplicadas"),
("AGR27", "Valuaciones"),
("AGR28", "Tecnologías de Información Geoespacial"),
("AGR29", "Planeamiento Urbano e Impacto Social y Ambiental"),
("IND01", "Principios de Ingeniería Industrial"),
("IND02", "Estática y Resistencia de Materiales"),
("IND03", "Organización y Dirección Empresaria"),
("IND04", "Probabilidad"),
("IND05", "Economía"),
("IND06", "Materiales y Aplicaciones I"),
("IND07", "Transformación de la Energía"),
("IND08", "Desarrollo Económico"),
("IND09", "Estadística Aplicada"),
("IND10", "Gestión Integral de la Cadena de Valor"),
("IND11", "Electrotecnia, Máquinas e Instalaciones Eléctricas"),
("IND12", "Investigación Operativa"),
("IND13", "Sistemas Contables y Gestión de Costos"),
("IND14", "Industrias Digitales"),
("IND15", "Ingeniería Ambiental, Sustentabilidad y Cuidado del Planeta"),
("IND16", "Ingeniería Económica"),
("IND17", "Equipos y Sistemas para Automatización Industrial"),
("IND18", "Industrias Químicas"),
("IND19", "Transformación de Materiales"),
("IND20", "Higiene y Seguridad"),
("IND21", "Industrias Extractivas"),
("IND22", "Proyecto Industrial"),
("ALI01", "Introducción a la Ingeniería en Alimentos"),
("ALI02", "Óptica"),
("ALI03", "Fundamentos de Procesos Químicos"),
("ALI04", "Laboratorio de Química"),
("ALI05", "Química de los compuestos orgánicos"),
("ALI06", "Termodinámica de los Procesos"),
("ALI07", "Fenómenos de Transporte"),
("ALI08", "Modelación Numérica"),
("ALI09", "Química Física"),
("ALI10", "Química Biológica y de Alimentos"),
("ALI11", "Microbiología General y de Alimentos"),
("ALI12", "Operaciones Unitarias de Transferencia de Cantidad de Movimiento y Energía"),
("ALI13", "Operaciones Unitarias de Transferencia de Materia"),
("ALI14", "Fundamentos de la Preservación de Alimentos I (FCEN)"),
("ALI15", "Química Analítica Instrumental"),
("ALI16", "Laboratorio de Operaciones y Procesos"),
("ALI17", "Instalaciones de Plantas de Procesos"),
("ALI18", "Fundamentos de la Preservación de Alimentos II (FCEN)"),
("ALI19", "Tecnología de Alimentos I (FCEN)"),
("ALI20", "Procesamiento de Alimentos en Planta Piloto (FCEN)"),
("ALI21", "Dinámica y Control de Procesos de Alimentos"),
("ALI22", "Legislación Alimentaria (FFyB)"),
("ALI23", "Tecnología de Alimentos II (bimestral)"),
("ALI24", "Tecnología de Alimentos III (bimestral)"),
("ALI25", "Biotecnología y Reactores para la Industria de Alimentos"),
("ALI26", "Gestión del Trabajo y del Ambiente en la Industria Alimentaria")
;
